### ISSUE TITLE
Coordenadas hypocentrales del Terremoto de ICA

### ISSUE THREAD

**Issue by gacandia** [sebacastroh/chileanSeismicDatabase#26]
Coordenadas hypocentrales del Terremoto de ICA (20010623_8.4M_17.21S_70.02W_25.7KM) son Lat: -16.36, Lon -73.48, Depth 32. El mecanismo es interface (no crustal)

**Comment by sebacastroh** [comment]
@gacandia efectivamente hay un error, pero me surge la duda de los valores a utilizar. El USGS reporta otra latitud, longitud y profundidad (cercanas a las que tú mencionas)

https://earthquake.usgs.gov/earthquakes/eventpage/official20010623203314130_33/executive

**Comment by gacandia** [comment]
Hola Sebastián, usa las del usgs no más
